[package]
name = "sun_prison"
version = "0.1.0"
authors = ["Dima Lazarev <dmitry.lazarev@gmail.com>"]
edition = "2018"

[dependencies]
bevy = "0.2.0"
# bevy = { git = "https://github.com/bevyengine/bevy" }